apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      name: sampleapp
  template:
    metadata:
      labels:
        name: sampleapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sampleapp
        image: jayaram011.azurecr.io/jayaramanbaskaranjayaram:77
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: sampleapp
